import json
from pathlib import Path
import sys
import tempfile


PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "runtime"))

from subtitle_text_reader import (
    SubtitleContentEmptyError,
    SubtitleFileNotFoundError,
    SubtitleFormatUnsupportedError,
    SubtitleSourceError,
    canonicalize_subtitle_text,
    read_subtitle_file,
    read_task_subtitle,
)


def write_status(folder: Path, result_type: str) -> None:
    (folder / "status.json").write_text(
        json.dumps({"ok": True, "type": result_type}), encoding="utf-8"
    )


def test_canonical_srt_removes_structure_and_preserves_text_punctuation():
    source = """\ufeff1\r
00:00:00,000 --> 00:00:01,500\r
<i>Hello,   world!</i>\r
\r
2\r
00:00:02,000 --> 00:00:03,000\r
{\\an8}Cafe\u0301  don’t.\r
"""
    assert canonicalize_subtitle_text(source, ".srt") == (
        "Hello, world!\nCafé don’t."
    )


def test_reader_selects_ocr_whisper_and_embedded_outputs():
    cases = [
        ("硬字幕 OCR", "硬字幕OCR文字.txt", "OCR text."),
        ("语音识别字幕", "语音识别文字.txt", "Whisper text."),
        ("极速语音识别字幕", "语音识别文字.txt", "Fast text."),
        ("视频字幕轨", "视频字幕轨.srt", "Embedded text."),
    ]
    with tempfile.TemporaryDirectory(prefix="vocab-reader-") as temp:
        root = Path(temp)
        for index, (result_type, filename, expected) in enumerate(cases):
            folder = root / str(index)
            folder.mkdir()
            write_status(folder, result_type)
            content = expected
            if filename.endswith(".srt"):
                content = f"1\n00:00:00,000 --> 00:00:01,000\n{expected}\n"
            (folder / filename).write_text(content, encoding="utf-8")
            document = read_task_subtitle(folder)
            assert document.canonical_text == expected
            assert document.source_type == result_type
            assert document.source_file_names == (filename,)


def test_reader_selects_one_english_remote_subtitle_without_merging_languages():
    with tempfile.TemporaryDirectory(prefix="vocab-remote-") as temp:
        folder = Path(temp)
        write_status(folder, "网页原字幕")
        (folder / "Episode.zh-Hans.srt").write_text(
            "1\n00:00:00,000 --> 00:00:01,000\n你好\n", encoding="utf-8"
        )
        (folder / "Episode.en-US.srt").write_text(
            "1\n00:00:00,000 --> 00:00:01,000\nHello there.\n", encoding="utf-8"
        )
        document = read_task_subtitle(folder)
        assert document.canonical_text == "Hello there."
        assert document.source_file_names == ("Episode.en-US.srt",)


def test_reader_rejects_ambiguous_remote_sources_and_supports_vtt_ass():
    with tempfile.TemporaryDirectory(prefix="vocab-formats-") as temp:
        root = Path(temp)
        ambiguous = root / "ambiguous"
        ambiguous.mkdir()
        write_status(ambiguous, "网页原字幕")
        (ambiguous / "one.srt").write_text("One", encoding="utf-8")
        (ambiguous / "two.srt").write_text("Two", encoding="utf-8")
        try:
            read_task_subtitle(ambiguous)
            raise AssertionError("ambiguous subtitle sources must fail")
        except SubtitleSourceError as exc:
            assert "多个" in str(exc)

        assert canonicalize_subtitle_text(
            "WEBVTT\n\n00:00.000 --> 00:01.000\n<b>VTT text.</b>\n", ".vtt"
        ) == "VTT text."
        ass = (
            "[Script Info]\nTitle: sample\n[Events]\n"
            "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
            "Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,{\\i1}ASS text.{\\i0}\\NNext\\hline.\n"
        )
        assert canonicalize_subtitle_text(ass, ".ass") == "ASS text.\nNext line."


def test_vtt_metadata_note_and_style_blocks_never_become_subtitle_text():
    source = """WEBVTT
Kind: captions
Language: en

STYLE
::cue { color: lime; }

NOTE generated by provider
this is metadata, not dialogue

cue-id
00:00.000 --> 00:01.000 align:start
&lt;b&gt;Real dialogue.&lt;/b&gt;
"""
    assert canonicalize_subtitle_text(source, ".vtt") == "Real dialogue."


def test_direct_file_reader_supports_srt_vtt_ass_and_txt_without_new_parsers():
    samples = {
        ".srt": "1\n00:00:00,000 --> 00:00:01,000\nSRT text.\n",
        ".vtt": "WEBVTT\n\n00:00.000 --> 00:01.000\nVTT text.\n",
        ".ass": (
            "[Events]\n"
            "Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,ASS text.\n"
        ),
        ".txt": "TXT text.\n",
    }
    with tempfile.TemporaryDirectory(prefix="vocab-direct-reader-") as temp:
        root = Path(temp)
        for suffix, content in samples.items():
            source = root / f"sample{suffix}"
            source.write_text(content, encoding="utf-8")
            document = read_subtitle_file(source)
            assert document.canonical_text == f"{suffix[1:].upper()} text."
            assert document.source_type == "手动字幕文件"
            assert document.source_file_names == (source.name,)


def test_direct_file_reader_distinguishes_missing_unsupported_and_empty_content():
    with tempfile.TemporaryDirectory(prefix="vocab-direct-errors-") as temp:
        root = Path(temp)
        cases = (
            (root / "missing.srt", SubtitleFileNotFoundError),
            (root / "subtitle.json", SubtitleFormatUnsupportedError),
            (root / "empty.srt", SubtitleContentEmptyError),
        )
        cases[1][0].write_text("English text.", encoding="utf-8")
        cases[2][0].write_text(
            "1\n00:00:00,000 --> 00:00:01,000\n   \n", encoding="utf-8"
        )
        for source, expected in cases:
            try:
                read_subtitle_file(source)
                raise AssertionError(f"{source.name} must fail")
            except expected:
                pass


if __name__ == "__main__":
    test_canonical_srt_removes_structure_and_preserves_text_punctuation()
    test_reader_selects_ocr_whisper_and_embedded_outputs()
    test_reader_selects_one_english_remote_subtitle_without_merging_languages()
    test_reader_rejects_ambiguous_remote_sources_and_supports_vtt_ass()
    test_vtt_metadata_note_and_style_blocks_never_become_subtitle_text()
    test_direct_file_reader_supports_srt_vtt_ass_and_txt_without_new_parsers()
    test_direct_file_reader_distinguishes_missing_unsupported_and_empty_content()
    print("PASS: subtitle text reader tests")
